theme = "catppuccin_mocha_bg"

[editor]
color-modes = true
true-color = true
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.gutters]
layout = ["line-numbers", "spacer", "diff", "diagnostics", ]

[editor.gutters.line-numbers]
min-width = 1

[keys.normal]
y = "yank_to_clipboard"

[keys.select]
y = "yank_to_clipboard"

[editor.whitespace.render]
tab = "all"

[editor.whitespace.characters]
tab = "▸"
